name: Lint

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install ESLint
        run: npm install -g eslint
      
      - name: Run ESLint with recommended rules
        run: eslint . --no-eslintrc --rule '{"extends": "eslint:recommended"}'